-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'HOUR_LOGGED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'HOUR_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'HOUR_REJECTED';
